---
abstract: 'Handy toolbox of things to ease development/debugging.'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Kit
no_index:
  directory:
    - t
    - inc
requires:
  Config::INI::Reader: 0
  Data::Dumper: 0
  Data::MessagePack: 0
  Digest::MD5: 0
  Digest::SHA: 0
  File::Slurp: 0
  File::Temp: 0
  HTML::Entities: 0
  Import::Into: 0
  JSON::Syck: 0
  MIME::Base64: 0
  MIME::QuotedPrint: 0
  Module::Want: 0
  Net::IDN::Encode: 0
  Storable: 0
  Test::More: 0
  URI::Escape: 0
  XML::Parser: 0
  YAML::Syck: 0
version: 0.2
